'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class barang
    Public Property kd_barang As String
    Public Property nm_barang As String
    Public Property diskon As Nullable(Of Double)
    Public Property hrg_jual As Nullable(Of Double)
    Public Property jumlah As Nullable(Of Double)
    Public Property rusak As Nullable(Of Double)
    Public Property sisa As Nullable(Of Double)

End Class
